/* tslint:disable */
/* eslint-disable */
/**
 * Patient Evidence Api
 * Patient Evidence and Prescription management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Prescription,
} from '../models';
import {
    PrescriptionFromJSON,
    PrescriptionToJSON,
} from '../models';

export interface CreatePrescriptionRequest {
    ambulanceId: string;
    patientId: string;
    prescription: Prescription;
}

export interface DeletePrescriptionRequest {
    ambulanceId: string;
    patientId: string;
    prescriptionId: string;
}

export interface GetPatientPrescriptionsRequest {
    ambulanceId: string;
    patientId: string;
}

export interface GetPrescriptionRequest {
    ambulanceId: string;
    patientId: string;
    prescriptionId: string;
}

export interface UpdatePrescriptionRequest {
    ambulanceId: string;
    patientId: string;
    prescriptionId: string;
    prescription: Prescription;
}

/**
 * PatientPrescriptionsApi - interface
 * 
 * @export
 * @interface PatientPrescriptionsApiInterface
 */
export interface PatientPrescriptionsApiInterface {
    /**
     * 
     * @summary Create a new prescription
     * @param {string} ambulanceId 
     * @param {string} patientId 
     * @param {Prescription} prescription 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientPrescriptionsApiInterface
     */
    createPrescriptionRaw(requestParameters: CreatePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Prescription>>;

    /**
     * Create a new prescription
     */
    createPrescription(requestParameters: CreatePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Prescription>;

    /**
     * 
     * @summary Delete prescription
     * @param {string} ambulanceId 
     * @param {string} patientId 
     * @param {string} prescriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientPrescriptionsApiInterface
     */
    deletePrescriptionRaw(requestParameters: DeletePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete prescription
     */
    deletePrescription(requestParameters: DeletePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Provides the list of prescriptions for a patient
     * @param {string} ambulanceId 
     * @param {string} patientId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientPrescriptionsApiInterface
     */
    getPatientPrescriptionsRaw(requestParameters: GetPatientPrescriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Prescription>>>;

    /**
     * Provides the list of prescriptions for a patient
     */
    getPatientPrescriptions(requestParameters: GetPatientPrescriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Prescription>>;

    /**
     * 
     * @summary Provides a single prescription
     * @param {string} ambulanceId 
     * @param {string} patientId 
     * @param {string} prescriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientPrescriptionsApiInterface
     */
    getPrescriptionRaw(requestParameters: GetPrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Prescription>>;

    /**
     * Provides a single prescription
     */
    getPrescription(requestParameters: GetPrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Prescription>;

    /**
     * 
     * @summary Update prescription
     * @param {string} ambulanceId 
     * @param {string} patientId 
     * @param {string} prescriptionId 
     * @param {Prescription} prescription 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientPrescriptionsApiInterface
     */
    updatePrescriptionRaw(requestParameters: UpdatePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Prescription>>;

    /**
     * Update prescription
     */
    updatePrescription(requestParameters: UpdatePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Prescription>;

}

/**
 * 
 */
export class PatientPrescriptionsApi extends runtime.BaseAPI implements PatientPrescriptionsApiInterface {

    /**
     * Create a new prescription
     */
    async createPrescriptionRaw(requestParameters: CreatePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Prescription>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling createPrescription.');
        }

        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling createPrescription.');
        }

        if (requestParameters.prescription === null || requestParameters.prescription === undefined) {
            throw new runtime.RequiredError('prescription','Required parameter requestParameters.prescription was null or undefined when calling createPrescription.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/evidence/{ambulanceId}/patients/{patientId}/prescriptions`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PrescriptionToJSON(requestParameters.prescription),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PrescriptionFromJSON(jsonValue));
    }

    /**
     * Create a new prescription
     */
    async createPrescription(requestParameters: CreatePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Prescription> {
        const response = await this.createPrescriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete prescription
     */
    async deletePrescriptionRaw(requestParameters: DeletePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling deletePrescription.');
        }

        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling deletePrescription.');
        }

        if (requestParameters.prescriptionId === null || requestParameters.prescriptionId === undefined) {
            throw new runtime.RequiredError('prescriptionId','Required parameter requestParameters.prescriptionId was null or undefined when calling deletePrescription.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/evidence/{ambulanceId}/patients/{patientId}/prescriptions/{prescriptionId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))).replace(`{${"prescriptionId"}}`, encodeURIComponent(String(requestParameters.prescriptionId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete prescription
     */
    async deletePrescription(requestParameters: DeletePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePrescriptionRaw(requestParameters, initOverrides);
    }

    /**
     * Provides the list of prescriptions for a patient
     */
    async getPatientPrescriptionsRaw(requestParameters: GetPatientPrescriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Prescription>>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getPatientPrescriptions.');
        }

        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling getPatientPrescriptions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/evidence/{ambulanceId}/patients/{patientId}/prescriptions`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PrescriptionFromJSON));
    }

    /**
     * Provides the list of prescriptions for a patient
     */
    async getPatientPrescriptions(requestParameters: GetPatientPrescriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Prescription>> {
        const response = await this.getPatientPrescriptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Provides a single prescription
     */
    async getPrescriptionRaw(requestParameters: GetPrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Prescription>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getPrescription.');
        }

        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling getPrescription.');
        }

        if (requestParameters.prescriptionId === null || requestParameters.prescriptionId === undefined) {
            throw new runtime.RequiredError('prescriptionId','Required parameter requestParameters.prescriptionId was null or undefined when calling getPrescription.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/evidence/{ambulanceId}/patients/{patientId}/prescriptions/{prescriptionId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))).replace(`{${"prescriptionId"}}`, encodeURIComponent(String(requestParameters.prescriptionId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PrescriptionFromJSON(jsonValue));
    }

    /**
     * Provides a single prescription
     */
    async getPrescription(requestParameters: GetPrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Prescription> {
        const response = await this.getPrescriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update prescription
     */
    async updatePrescriptionRaw(requestParameters: UpdatePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Prescription>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling updatePrescription.');
        }

        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling updatePrescription.');
        }

        if (requestParameters.prescriptionId === null || requestParameters.prescriptionId === undefined) {
            throw new runtime.RequiredError('prescriptionId','Required parameter requestParameters.prescriptionId was null or undefined when calling updatePrescription.');
        }

        if (requestParameters.prescription === null || requestParameters.prescription === undefined) {
            throw new runtime.RequiredError('prescription','Required parameter requestParameters.prescription was null or undefined when calling updatePrescription.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/evidence/{ambulanceId}/patients/{patientId}/prescriptions/{prescriptionId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))).replace(`{${"prescriptionId"}}`, encodeURIComponent(String(requestParameters.prescriptionId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PrescriptionToJSON(requestParameters.prescription),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PrescriptionFromJSON(jsonValue));
    }

    /**
     * Update prescription
     */
    async updatePrescription(requestParameters: UpdatePrescriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Prescription> {
        const response = await this.updatePrescriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
