/* tslint:disable */
/* eslint-disable */
/**
 * Patient Evidence Api
 * Patient Evidence and Prescription management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EvidedPatient,
} from '../models';
import {
    EvidedPatientFromJSON,
    EvidedPatientToJSON,
} from '../models';

export interface CreateEvidedPatientRequest {
    ambulanceId: string;
    evidedPatient: EvidedPatient;
}

export interface DeleteEvidedPatientRequest {
    ambulanceId: string;
    patientId: string;
}

export interface GetEvidedPatientRequest {
    ambulanceId: string;
    patientId: string;
}

export interface GetEvidedPatientsRequest {
    ambulanceId: string;
}

export interface UpdateEvidedPatientRequest {
    ambulanceId: string;
    patientId: string;
    evidedPatient: EvidedPatient;
}

/**
 * PatientEvidenceApi - interface
 * 
 * @export
 * @interface PatientEvidenceApiInterface
 */
export interface PatientEvidenceApiInterface {
    /**
     * Creates a new patient record at the given ambulance
     * @summary Register a new patient
     * @param {string} ambulanceId 
     * @param {EvidedPatient} evidedPatient 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientEvidenceApiInterface
     */
    createEvidedPatientRaw(requestParameters: CreateEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvidedPatient>>;

    /**
     * Creates a new patient record at the given ambulance
     * Register a new patient
     */
    createEvidedPatient(requestParameters: CreateEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvidedPatient>;

    /**
     * 
     * @summary Delete patient record
     * @param {string} ambulanceId 
     * @param {string} patientId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientEvidenceApiInterface
     */
    deleteEvidedPatientRaw(requestParameters: DeleteEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete patient record
     */
    deleteEvidedPatient(requestParameters: DeleteEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Provides a single patient record
     * @param {string} ambulanceId 
     * @param {string} patientId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientEvidenceApiInterface
     */
    getEvidedPatientRaw(requestParameters: GetEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvidedPatient>>;

    /**
     * Provides a single patient record
     */
    getEvidedPatient(requestParameters: GetEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvidedPatient>;

    /**
     * Returns all patients registered at the given ambulance
     * @summary Provides the list of evidenced patients
     * @param {string} ambulanceId id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientEvidenceApiInterface
     */
    getEvidedPatientsRaw(requestParameters: GetEvidedPatientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EvidedPatient>>>;

    /**
     * Returns all patients registered at the given ambulance
     * Provides the list of evidenced patients
     */
    getEvidedPatients(requestParameters: GetEvidedPatientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EvidedPatient>>;

    /**
     * 
     * @summary Update patient record
     * @param {string} ambulanceId 
     * @param {string} patientId 
     * @param {EvidedPatient} evidedPatient 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PatientEvidenceApiInterface
     */
    updateEvidedPatientRaw(requestParameters: UpdateEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvidedPatient>>;

    /**
     * Update patient record
     */
    updateEvidedPatient(requestParameters: UpdateEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvidedPatient>;

}

/**
 * 
 */
export class PatientEvidenceApi extends runtime.BaseAPI implements PatientEvidenceApiInterface {

    /**
     * Creates a new patient record at the given ambulance
     * Register a new patient
     */
    async createEvidedPatientRaw(requestParameters: CreateEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvidedPatient>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling createEvidedPatient.');
        }

        if (requestParameters.evidedPatient === null || requestParameters.evidedPatient === undefined) {
            throw new runtime.RequiredError('evidedPatient','Required parameter requestParameters.evidedPatient was null or undefined when calling createEvidedPatient.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/evidence/{ambulanceId}/patients`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EvidedPatientToJSON(requestParameters.evidedPatient),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EvidedPatientFromJSON(jsonValue));
    }

    /**
     * Creates a new patient record at the given ambulance
     * Register a new patient
     */
    async createEvidedPatient(requestParameters: CreateEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvidedPatient> {
        const response = await this.createEvidedPatientRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete patient record
     */
    async deleteEvidedPatientRaw(requestParameters: DeleteEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling deleteEvidedPatient.');
        }

        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling deleteEvidedPatient.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/evidence/{ambulanceId}/patients/{patientId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete patient record
     */
    async deleteEvidedPatient(requestParameters: DeleteEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEvidedPatientRaw(requestParameters, initOverrides);
    }

    /**
     * Provides a single patient record
     */
    async getEvidedPatientRaw(requestParameters: GetEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvidedPatient>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getEvidedPatient.');
        }

        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling getEvidedPatient.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/evidence/{ambulanceId}/patients/{patientId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EvidedPatientFromJSON(jsonValue));
    }

    /**
     * Provides a single patient record
     */
    async getEvidedPatient(requestParameters: GetEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvidedPatient> {
        const response = await this.getEvidedPatientRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all patients registered at the given ambulance
     * Provides the list of evidenced patients
     */
    async getEvidedPatientsRaw(requestParameters: GetEvidedPatientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EvidedPatient>>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getEvidedPatients.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/evidence/{ambulanceId}/patients`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EvidedPatientFromJSON));
    }

    /**
     * Returns all patients registered at the given ambulance
     * Provides the list of evidenced patients
     */
    async getEvidedPatients(requestParameters: GetEvidedPatientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EvidedPatient>> {
        const response = await this.getEvidedPatientsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update patient record
     */
    async updateEvidedPatientRaw(requestParameters: UpdateEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvidedPatient>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling updateEvidedPatient.');
        }

        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling updateEvidedPatient.');
        }

        if (requestParameters.evidedPatient === null || requestParameters.evidedPatient === undefined) {
            throw new runtime.RequiredError('evidedPatient','Required parameter requestParameters.evidedPatient was null or undefined when calling updateEvidedPatient.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/evidence/{ambulanceId}/patients/{patientId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EvidedPatientToJSON(requestParameters.evidedPatient),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EvidedPatientFromJSON(jsonValue));
    }

    /**
     * Update patient record
     */
    async updateEvidedPatient(requestParameters: UpdateEvidedPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvidedPatient> {
        const response = await this.updateEvidedPatientRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
