/* tslint:disable */
/* eslint-disable */
/**
 * Patient Evidence Api
 * Patient Evidence and Prescription management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvidedPatient
 */
export interface EvidedPatient {
    /**
     * Unique id of the patient record
     * @type {string}
     * @memberof EvidedPatient
     */
    id: string;
    /**
     * Full name of the patient
     * @type {string}
     * @memberof EvidedPatient
     */
    name: string;
    /**
     * Slovak national identification number
     * @type {string}
     * @memberof EvidedPatient
     */
    rodneCislo: string;
    /**
     * 
     * @type {Date}
     * @memberof EvidedPatient
     */
    dateOfBirth: Date;
    /**
     * 
     * @type {string}
     * @memberof EvidedPatient
     */
    gender: EvidedPatientGenderEnum;
    /**
     * 
     * @type {string}
     * @memberof EvidedPatient
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof EvidedPatient
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof EvidedPatient
     */
    email?: string;
    /**
     * Health insurance company
     * @type {string}
     * @memberof EvidedPatient
     */
    insurance: EvidedPatientInsuranceEnum;
    /**
     * 
     * @type {string}
     * @memberof EvidedPatient
     */
    bloodType?: EvidedPatientBloodTypeEnum;
    /**
     * Free-text list of known allergies
     * @type {string}
     * @memberof EvidedPatient
     */
    allergies?: string;
    /**
     * Free-text list of chronic conditions
     * @type {string}
     * @memberof EvidedPatient
     */
    chronicConditions?: string;
    /**
     * Free-text list of long-term medications
     * @type {string}
     * @memberof EvidedPatient
     */
    medications?: string;
}


/**
 * @export
 */
export const EvidedPatientGenderEnum = {
    Male: 'male',
    Female: 'female',
    Other: 'other'
} as const;
export type EvidedPatientGenderEnum = typeof EvidedPatientGenderEnum[keyof typeof EvidedPatientGenderEnum];

/**
 * @export
 */
export const EvidedPatientInsuranceEnum = {
    Vzp: 'VšZP',
    Dvera: 'Dôvera',
    Union: 'Union'
} as const;
export type EvidedPatientInsuranceEnum = typeof EvidedPatientInsuranceEnum[keyof typeof EvidedPatientInsuranceEnum];

/**
 * @export
 */
export const EvidedPatientBloodTypeEnum = {
    A_POSITIVE: 'A+',
    A_NEGATIVE: 'A-',
    B_POSITIVE: 'B+',
    B_NEGATIVE: 'B-',
    AB_POSITIVE: 'AB+',
    AB_NEGATIVE: 'AB-',
    O_POSITIVE: '0+',
    O_NEGATIVE: '0-'
} as const;
export type EvidedPatientBloodTypeEnum = typeof EvidedPatientBloodTypeEnum[keyof typeof EvidedPatientBloodTypeEnum];


/**
 * Check if a given object implements the EvidedPatient interface.
 */
export function instanceOfEvidedPatient(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "rodneCislo" in value;
    isInstance = isInstance && "dateOfBirth" in value;
    isInstance = isInstance && "gender" in value;
    isInstance = isInstance && "insurance" in value;

    return isInstance;
}

export function EvidedPatientFromJSON(json: any): EvidedPatient {
    return EvidedPatientFromJSONTyped(json, false);
}

export function EvidedPatientFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvidedPatient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'rodneCislo': json['rodneCislo'],
        'dateOfBirth': (new Date(json['dateOfBirth'])),
        'gender': json['gender'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'insurance': json['insurance'],
        'bloodType': !exists(json, 'bloodType') ? undefined : json['bloodType'],
        'allergies': !exists(json, 'allergies') ? undefined : json['allergies'],
        'chronicConditions': !exists(json, 'chronicConditions') ? undefined : json['chronicConditions'],
        'medications': !exists(json, 'medications') ? undefined : json['medications'],
    };
}

export function EvidedPatientToJSON(value?: EvidedPatient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'rodneCislo': value.rodneCislo,
        'dateOfBirth': (value.dateOfBirth.toISOString().substr(0,10)),
        'gender': value.gender,
        'address': value.address,
        'phone': value.phone,
        'email': value.email,
        'insurance': value.insurance,
        'bloodType': value.bloodType,
        'allergies': value.allergies,
        'chronicConditions': value.chronicConditions,
        'medications': value.medications,
    };
}

