/* tslint:disable */
/* eslint-disable */
/**
 * Patient Evidence Api
 * Patient Evidence and Prescription management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Prescription
 */
export interface Prescription {
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    medicineName: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    strength: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    form: PrescriptionFormEnum;
    /**
     * Dosing schedule (morning-noon-evening-night)
     * @type {string}
     * @memberof Prescription
     */
    dosage: string;
    /**
     * Free-text patient instructions
     * @type {string}
     * @memberof Prescription
     */
    instructions?: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    quantity: string;
    /**
     * Anatomical Therapeutic Chemical classification code
     * @type {string}
     * @memberof Prescription
     */
    atcCode?: string;
    /**
     * 
     * @type {Date}
     * @memberof Prescription
     */
    prescribedDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Prescription
     */
    validUntil: Date;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    prescribedBy: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    status: PrescriptionStatusEnum;
    /**
     * Repeat prescription period in months (1 = single use)
     * @type {number}
     * @memberof Prescription
     */
    repeatMonths?: PrescriptionRepeatMonthsEnum;
    /**
     * Insurance coverage level
     * @type {string}
     * @memberof Prescription
     */
    coverage?: PrescriptionCoverageEnum;
}


/**
 * @export
 */
export const PrescriptionFormEnum = {
    Tbl: 'tbl.',
    Kapsule: 'kapsule',
    Sirup: 'sirup',
    Kvapky: 'kvapky',
    Mas: 'masť',
    Krm: 'krém',
    Injekcia: 'injekcia',
    Inhaltor: 'inhalátor',
    Apk: 'čapík'
} as const;
export type PrescriptionFormEnum = typeof PrescriptionFormEnum[keyof typeof PrescriptionFormEnum];

/**
 * @export
 */
export const PrescriptionStatusEnum = {
    Active: 'active',
    Dispensed: 'dispensed',
    Expired: 'expired'
} as const;
export type PrescriptionStatusEnum = typeof PrescriptionStatusEnum[keyof typeof PrescriptionStatusEnum];

/**
 * @export
 */
export const PrescriptionRepeatMonthsEnum = {
    NUMBER_1: 1,
    NUMBER_3: 3,
    NUMBER_6: 6,
    NUMBER_12: 12
} as const;
export type PrescriptionRepeatMonthsEnum = typeof PrescriptionRepeatMonthsEnum[keyof typeof PrescriptionRepeatMonthsEnum];

/**
 * @export
 */
export const PrescriptionCoverageEnum = {
    Full: 'full',
    Partial: 'partial',
    None: 'none'
} as const;
export type PrescriptionCoverageEnum = typeof PrescriptionCoverageEnum[keyof typeof PrescriptionCoverageEnum];


/**
 * Check if a given object implements the Prescription interface.
 */
export function instanceOfPrescription(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "medicineName" in value;
    isInstance = isInstance && "strength" in value;
    isInstance = isInstance && "form" in value;
    isInstance = isInstance && "dosage" in value;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "prescribedDate" in value;
    isInstance = isInstance && "validUntil" in value;
    isInstance = isInstance && "prescribedBy" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function PrescriptionFromJSON(json: any): Prescription {
    return PrescriptionFromJSONTyped(json, false);
}

export function PrescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Prescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'medicineName': json['medicineName'],
        'strength': json['strength'],
        'form': json['form'],
        'dosage': json['dosage'],
        'instructions': !exists(json, 'instructions') ? undefined : json['instructions'],
        'quantity': json['quantity'],
        'atcCode': !exists(json, 'atcCode') ? undefined : json['atcCode'],
        'prescribedDate': (new Date(json['prescribedDate'])),
        'validUntil': (new Date(json['validUntil'])),
        'prescribedBy': json['prescribedBy'],
        'status': json['status'],
        'repeatMonths': !exists(json, 'repeatMonths') ? undefined : json['repeatMonths'],
        'coverage': !exists(json, 'coverage') ? undefined : json['coverage'],
    };
}

export function PrescriptionToJSON(value?: Prescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'medicineName': value.medicineName,
        'strength': value.strength,
        'form': value.form,
        'dosage': value.dosage,
        'instructions': value.instructions,
        'quantity': value.quantity,
        'atcCode': value.atcCode,
        'prescribedDate': (value.prescribedDate.toISOString().substr(0,10)),
        'validUntil': (value.validUntil.toISOString().substr(0,10)),
        'prescribedBy': value.prescribedBy,
        'status': value.status,
        'repeatMonths': value.repeatMonths,
        'coverage': value.coverage,
    };
}

