/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GregorHiresProjectEvidenceList {
    }
}
declare global {
    interface HTMLGregorHiresProjectEvidenceListElement extends Components.GregorHiresProjectEvidenceList, HTMLStencilElement {
    }
    var HTMLGregorHiresProjectEvidenceListElement: {
        prototype: HTMLGregorHiresProjectEvidenceListElement;
        new (): HTMLGregorHiresProjectEvidenceListElement;
    };
    interface HTMLElementTagNameMap {
        "gregor-hires-project-evidence-list": HTMLGregorHiresProjectEvidenceListElement;
    }
}
declare namespace LocalJSX {
    interface GregorHiresProjectEvidenceList {
    }
    interface IntrinsicElements {
        "gregor-hires-project-evidence-list": GregorHiresProjectEvidenceList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gregor-hires-project-evidence-list": LocalJSX.IntrinsicElements["gregor-hires-project-evidence-list"] & JSXBase.HTMLAttributes<HTMLGregorHiresProjectEvidenceListElement>;
        }
    }
}
